version = 1

exclude_patterns = [
  "frontend/wailsjs/**",
  "vendor/**"
]

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/benni347/messenger"
  dependencies_vendored = true

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "prettier"
