// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Retrieve(arg1, arg2) {
  return window['go']['main']['App']['Retrieve'](arg1, arg2);
}

export function RetrieveEnvValues() {
  return window['go']['main']['App']['RetrieveEnvValues']();
}

export function Store(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Store'](arg1, arg2, arg3, arg4);
}
