// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateChatRoomId(arg1:string,arg2:string):Promise<string>;

export function GenerateUserName(arg1:number):Promise<string>;

export function GetAppId():Promise<string>;

export function GetAppKey():Promise<string>;

export function GetAppSecret():Promise<string>;

export function GetClusterId():Promise<string>;

export function GetRabbitMqAdmin():Promise<string>;

export function GetRabbitMqHost():Promise<string>;

export function GetRabbitMqPassword():Promise<string>;

export function GetSupaBaseApiKey():Promise<string>;

export function GetSupaBaseUrl():Promise<string>;

export function Receive():Promise<any>;

export function ReciveFormatForJs():Promise<string>;

export function RetrieveEnvValues():Promise<main.Config>;

export function Send(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetQueuName(arg1:string):Promise<void>;

export function ValidateEmail(arg1:string):Promise<boolean>;
