// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAppId():Promise<string>;

export function GetAppKey():Promise<string>;

export function GetAppSecret():Promise<string>;

export function GetClusterId():Promise<string>;

export function GetSupaBaseApiKey():Promise<string>;

export function GetSupaBaseUrl():Promise<string>;

export function RetrieveEnvValues():Promise<main.Config>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ValidateEmail(arg1:string):Promise<boolean>;
