// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Retrieve(arg1:any,arg2:number):Promise<Array<main.Message>>;

export function RetrieveEnvValues():Promise<main.Config>;

export function Store(arg1:any,arg2:number,arg3:string,arg4:string):Promise<void>;
