// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChatRoomId(arg1, arg2) {
  return window['go']['main']['App']['CreateChatRoomId'](arg1, arg2);
}

export function GenerateUserName(arg1) {
  return window['go']['main']['App']['GenerateUserName'](arg1);
}

export function GetAppId() {
  return window['go']['main']['App']['GetAppId']();
}

export function GetAppKey() {
  return window['go']['main']['App']['GetAppKey']();
}

export function GetAppSecret() {
  return window['go']['main']['App']['GetAppSecret']();
}

export function GetClusterId() {
  return window['go']['main']['App']['GetClusterId']();
}

export function GetOtherUserId(arg1, arg2) {
  return window['go']['main']['App']['GetOtherUserId'](arg1, arg2);
}

export function GetRabbitMqAdmin() {
  return window['go']['main']['App']['GetRabbitMqAdmin']();
}

export function GetRabbitMqHost() {
  return window['go']['main']['App']['GetRabbitMqHost']();
}

export function GetRabbitMqPassword() {
  return window['go']['main']['App']['GetRabbitMqPassword']();
}

export function GetSupaBaseApiKey() {
  return window['go']['main']['App']['GetSupaBaseApiKey']();
}

export function GetSupaBaseUrl() {
  return window['go']['main']['App']['GetSupaBaseUrl']();
}

export function Receive(arg1) {
  return window['go']['main']['App']['Receive'](arg1);
}

export function ReciveFormatForJs(arg1) {
  return window['go']['main']['App']['ReciveFormatForJs'](arg1);
}

export function RetrieveEnvValues() {
  return window['go']['main']['App']['RetrieveEnvValues']();
}

export function Send(arg1, arg2) {
  return window['go']['main']['App']['Send'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetQueuName(arg1) {
  return window['go']['main']['App']['SetQueuName'](arg1);
}

export function ValidateEmail(arg1) {
  return window['go']['main']['App']['ValidateEmail'](arg1);
}
