// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePeerConnection() {
  return window["go"]["main"]["App"]["CreatePeerConnection"]();
}

export function Disconnect() {
  return window["go"]["main"]["App"]["Disconnect"]();
}
